### PR TITLE
Fix Results Pagination

### LINKED ISSUE #264: Results Page Pagination Issues
You are able to navigate to the next race's results (and enter then) even if it is not closed yet. This causes a race to become inaccessible via the UI if it is not yet closed but results are entered.

This can be fixed using the bulk results endpoint at api/results/bulk?e=x and adding guards.

OR (probably better) rendering the correct next & previous races server side instead of handling with Vue. This would eliminate the messy setPrevAndNextRaces() method AND speed up the load time.

### PR DESCRIPTION
**Pull request by nicholasklaene**
Results pagination is now rendered server side & correctly routes to races (never routes to race that is still open).

Fixes #264

### CODE REVIEW

File: public_html/admin-v2/races/js/results.js [hunk 1]
```diff
@@ -29,31 +27,48 @@ const results = new Vue({
...
-      return this.horses.filter(horse => horse.id != placeId && horse.id != showId);
+      return this.horses.filter(
+        (horse) => horse.id != placeId && horse.id != showId
+      );
     },
     availablePlaceHorses: function () {
       const winId = this.enteredResults.win;
       const showId = this.enteredResults.show;
-      return this.horses.filter(horse => horse.id != winId && horse.id != showId);
+      return this.horses.filter(
```
Comment (makungaj1) [inline public_html/admin-v2/races/js/results.js:37]: Can you create util.js file and encapsulate this?? So we can reuse it in multiple files.

**Review by makungaj1 — CHANGES_REQUESTED** [review]
Everything else look fine

File: public_html/admin-v2/races/js/results.js (hunk 1 above)
Comment (nicholasklaene) [reply public_html/admin-v2/races/js/results.js:37]: The filter statement is slightly different in all 3 computed properties. 

Also the logic needs to be inside the computed property or their may be some errors
https://vuejs.org/v2/guide/computed.html
