### PR TITLE
Fix Large Purse Sizes on Results Page

### LINKED ISSUE #263: 500 Internal Server Error With Large Pot Sizes on Results Page
Large purse sizes cause an internal server error.

Add client side guards to prevent this from happening.

### PR DESCRIPTION
**Pull request by nicholasklaene**
Restrict numbers to be <= 9999.99 & fix them to at most 2 decimal places. Fixes #263

### CODE REVIEW

File: public_html/admin-v2/races/js/results.js [hunk 1]
```diff
@@ -29,31 +29,48 @@ const results = new Vue({
     availableWinHorses: function () {
       const placeId = this.enteredResults.place;
       const showId = this.enteredResults.show;
-      return this.horses.filter(horse => horse.id != placeId && horse.id != showId);
+      return this.horses.filter(
```
Comment (makungaj1) [inline public_html/admin-v2/races/js/results.js:32]: Can we encapsulate this logic and reuse it? Just to have a single place of truth.
